import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {Game,metrics,desiredSpeed,displayedSpeed,poseFor,advice,itemScrollSpeed} from '../dist/model.js';
import {CONFIG as C} from '../dist/config.js';
import {byId,FOODS} from '../dist/foods.js';
import {wheelGeometry} from '../dist/geometry.js';
import {BIKE_MANIFEST} from '../dist/bike-manifest.js';
const food=byId('rice'),water=byId('water'),snack=byId('candy'),bad=byId('badbread');
const records=(counts,time=0)=>counts.flatMap((n,group)=>Array.from({length:n},()=>({group,kind:'food',time})));
test('15km/h launch accelerates gently, pause freezes it and restart returns to 15',()=>{const g=new Game();g.nextSpawn=100;assert.equal(g.displayedSpeedKmh,15);assert.equal(displayedSpeed(g.speed),15);g.step(1);assert.equal(g.displayedSpeedKmh,23);const before=[g.time,g.speed];g.step(0);assert.deepEqual([g.time,g.speed],before);g.step(2);assert.equal(g.displayedSpeedKmh,39);g.step(4);assert.equal(g.displayedSpeedKmh,50);g.reset();assert.equal(g.displayedSpeedKmh,15);assert.equal(displayedSpeed(g.speed),15);});
test('exact nutrition equations, empty and optimal state',()=>{assert.equal(metrics([],75,0).F,0);assert.equal(metrics([],75,0).I,0);const m=metrics(records(C.targets),100,0);assert.equal(m.F,1);assert.equal(m.I,0);assert.equal(desiredSpeed(m),30);assert.equal(displayedSpeed(desiredSpeed(m)),100);});
test('over-target food still counts toward imbalance; varied food recovers',()=>{const one=metrics(records([12,0,0,0,0]),75,0);assert.equal(one.F,.2);assert.ok(one.I>.9);const recovered=metrics(records([12,10,12,10,10]),75,0);assert.equal(recovered.F,1);assert.equal(recovered.I,0);assert.ok(desiredSpeed(recovered)>desiredSpeed(one));});
test('no imbalance penalty below five foods',()=>assert.equal(metrics(records([4,0,0,0,0]),75,0).I,0));
test('snacks 0–2 free; third penalizes; expires at 20s',()=>{const r=records(C.targets);for(let i=0;i<2;i++)r.push({kind:'snack',time:0});assert.equal(metrics(r,100,0).K,0);r.push({kind:'snack',time:0});assert.equal(metrics(r,100,0).K,1);assert.equal(metrics(r,100,20).K,0);assert.equal(metrics(records(C.targets),100,0).F,1);});
test('water recovers hydration but never clears nutrition or snack history',()=>{const g=new Game();g.records=records([10,0,0,0,0]);g.take(snack);g.water=0;const before=metrics(g.records,0,g.time);g.take(water);const after=metrics(g.records,g.water,g.time);assert.equal(g.water,30);assert.equal(after.I,before.I);assert.equal(after.snacks,1);assert.equal(after.H,0);assert.ok(desiredSpeed(metrics(records(C.targets),30,0))>desiredSpeed(metrics(records(C.targets),0,0)));g.water=100;g.take(water);assert.equal(g.water,100);});
test('spoiled food slows immediately, renews 3s once, adds no nutrition',()=>{const g=new Game();g.time=10;g.records=records(C.targets,10);g.water=100;g.speed=30;g.take(bad);assert.equal(g.speed,19.5);assert.equal(g.records.length,12);assert.equal(g.spoiledUntil,13);g.time=11;g.take(bad);assert.equal(g.spoiledUntil,14);assert.equal(g.speed,19.5);g.items=[];g.nextSpawn=100;g.step(3.5);assert.ok(g.speed>29);});
test('water shortage and all worst states retain minimum movement',()=>{const m=metrics([...records([20,0,0,0,0]),...Array.from({length:4},()=>({kind:'snack',time:0}))],0,0);assert.equal(desiredSpeed(m,true),8);const g=new Game();g.water=0;g.items=[];g.nextSpawn=100;g.step(1);assert.ok(g.distance>0);assert.equal(g.finishSnapshot,null);});
test('integer display and 70/65 hysteresis share the same value',()=>{assert.equal(displayedSpeed(20.85),70);assert.equal(poseFor(false,69),false);assert.equal(poseFor(false,70),true);assert.equal(poseFor(true,68),true);assert.equal(poseFor(true,66),true);assert.equal(poseFor(true,65),false);});
test('69 vs 70 vs 100 finish and 68km/h fast pose; timeout never gets ending',()=>{for(const [kmh,success,ending] of [[69,true,false],[70,true,true],[100,true,true],[68,true,false],[100,false,false]]){const g=new Game();g.fast=true;g.displayedSpeedKmh=kmh;g.finish(success);const s=g.finishSnapshot;assert.equal(s.hasHighSpeedEnding,ending);g.speed=0;g.displayedSpeedKmh=0;g.finish(!success);assert.equal(g.finishSnapshot,s);assert.equal(s.finishSpeedKmh,kmh);}});
test('arrival exactly at 60s succeeds; crossing after 60s fails',()=>{const g=new Game();g.time=59.99;g.distance=C.finishDistance-.15;g.speed=15;g.items=[];g.nextSpawn=100;g.step(.2);assert.equal(g.finishSnapshot.success,true);assert.ok(g.finishSnapshot.time<=60);const fail=new Game();fail.time=59.99;fail.distance=C.finishDistance-1;fail.items=[];fail.nextSpawn=100;fail.step(.2);assert.equal(fail.finishSnapshot.success,false);assert.equal(fail.finishSnapshot.time,60);});
test('front-wheel shadow processes an item once; touching rider alone does not collect',()=>{const g=new Game();g.nextSpawn=100;g.items=[{id:1,x:C.bike.pickup.x,y:g.y+C.bike.groundDY,food,taken:false}];g.step(.1);assert.equal(g.totals[0],1);g.step(.1);assert.equal(g.totals[0],1);g.items=[{id:2,x:C.bike.x,y:g.y,food,taken:false}];g.step(.1);assert.equal(g.totals[0],1);g.finish(true);g.reset();assert.equal(g.records.length,0);assert.equal(g.finishSnapshot,null);assert.equal(g.spoiledUntil,0);assert.equal(g.totals.reduce((a,b)=>a+b),0);});
test('different wheel sizes, imbalance and low water retain shared ground contacts',()=>{for(const counts of [[0,0,0,0,0],C.targets,[12,0,0,0,0]])for(const waterLevel of [0,20,75,100])for(let i=0;i<96;i++){const m=metrics(records(counts),waterLevel,0),w=wheelGeometry(m,i*Math.PI/48);assert.ok(Math.abs(w.rearY+w.rearSupport-C.bike.groundDY)<1e-8);assert.ok(Math.abs(w.frontY+w.frontSupport-C.bike.groundDY)<1e-8);assert.ok(w.frontY>w.rearY);}});
test('continuous food heights include the middle of the track, stagger x, all positions reachable',()=>{const g=new Game(44);const heights=[];for(let i=0;i<80;i++){g.time=i*1.2;g.spawn();const pair=g.items.splice(0);assert.ok(pair[1].x-pair[0].x>=C.itemStagger);for(const it of pair){heights.push(it.y);assert.ok(it.y>=C.bike.minY+C.bike.groundDY&&it.y<=C.bike.maxY+C.bike.groundDY);}}const start=C.bike.minY+C.bike.groundDY,end=C.bike.maxY+C.bike.groundDY;for(let bin=0;bin<5;bin++)assert.ok(heights.some(y=>Math.floor((y-start)/(end-start)*5)===bin));assert.ok(C.scenery.road/C.pixelDistanceScale>=4);});
test('fair scheduler, top-speed thinking time, first 5s safe',()=>{const g=new Game(13);for(let t=0;t<60;t+=1.2){g.time=t;g.spawn();if(t>=10)assert.ok(g.lastOffered.every(last=>t-last<8),JSON.stringify({t,last:g.lastOffered}));assert.ok(t-g.lastWater<=6);if(t<5)assert.ok(g.items.every(i=>i.food.kind!=='spoiled'));g.items=[];}assert.ok((C.itemStartX-C.bike.pickup.x-C.bike.pickup.rx-C.itemRadius)/itemScrollSpeed(C.maxInternalSpeed)>=1.7);});
test('advice never tells the player to fill sugar and recognizes full balance',()=>{assert.match(advice(metrics(records(C.targets),100,0),100),/균형 좋아요/);assert.match(advice(metrics([],0,0),0),/물/);});
test('new pack assets, all eight source rectangles, food icons and original endings',()=>{const m=BIKE_MANIFEST;assert.equal(Object.keys(m.frames).length,8);for(const f of Object.values(m.frames)){const [x,y,w,h]=f.sourceRect;assert.ok(x>=0&&y>=0&&w>0&&h>0&&x+w<=m.sheetSize[0]&&y+h<=m.sheetSize[1]);}for(const p of Object.values(m.assets))assert.ok(fs.existsSync(new URL('../dist/'+C.bike.pack.base+'/'+p,import.meta.url)));for(const f of FOODS)assert.ok(fs.existsSync(new URL('../dist/'+f.image,import.meta.url)));for(const e of C.endings)assert.ok(fs.existsSync(new URL('../dist/'+e.path,import.meta.url)));});

function play(seed,mode='balanced'){
 const g=new Game(seed);let chosen=null;for(let i=0;i<60*60&&!g.finishSnapshot;i++){
  // Controlled single-group intake: omitted choices represent intentionally
  // passing every other food; retain water to isolate nutrition imbalance.
  if(mode==='grain')g.items=g.items.filter(it=>it.food.group===0||it.food.kind==='water');
  const pass=C.bike.pickup.x-C.bike.pickup.rx-C.itemRadius;
  if(!chosen||!g.items.includes(chosen)||chosen.x<pass){const row=g.items.filter(it=>it.x>pass).sort((a,b)=>a.x-b.x);if(row.length){const nearest=row[0].x;const options=row.filter(it=>Math.abs(it.x-nearest)<5);const score=it=>{const f=it.food;if(f.kind==='water')return g.water<65?4:0;if(mode==='grain')return f.group===0?5:-10;if(f.kind!=='food')return -10;return 2-g.m.counts[f.group]/C.targets[f.group]+(g.m.proportions[f.group]<g.m.weights[f.group]?.3:0);};options.sort((a,b)=>score(b)-score(a));chosen=options[0];if(score(chosen)<0)chosen=null;}}
  if(chosen)g.targetY=chosen.y-C.bike.groundDY;else {const danger=g.items.filter(it=>it.x>pass).sort((a,b)=>a.x-b.x)[0];g.targetY=danger&&danger.y<(C.bike.minY+C.bike.maxY)/2+C.bike.groundDY?C.bike.maxY:C.bike.minY;}g.step(1/60);
 }return g.finishSnapshot;
}
test('balanced controller finishes within 60 seconds across 20 seeds; imbalanced choices struggle',()=>{const runs=Array.from({length:20},(_,i)=>play(i+1));assert.ok(runs.every(r=>r.success));assert.ok(runs.every(r=>r.time>0&&r.time<=C.timeLimit),JSON.stringify(runs.map(r=>r.time)));console.log('Balanced play times:',runs.map(r=>r.time.toFixed(1)).join(', '));const bad=play(3,'grain');assert.equal(bad.success,false);});
