import test from 'node:test';import assert from 'node:assert/strict';
import {Game,metrics,desiredSpeed,itemScrollSpeed} from '../dist/model.js';import {CONFIG as C} from '../dist/config.js';import {byId,FOODS} from '../dist/foods.js';import {foodAppearance,spaceTarget} from '../dist/view.js';
function fullRecords(){return C.targets.flatMap((n,group)=>Array.from({length:n},()=>({kind:'food',group,foodId:FOODS.find(f=>f.group===group).id,time:0})));}
test('food approach speed increases throughout play and stops at zero',()=>{assert.equal(itemScrollSpeed(0),0);assert.equal(itemScrollSpeed(15),225);assert.equal(itemScrollSpeed(30),300);for(let speed=8;speed<30;speed++)assert.ok(itemScrollSpeed(speed+1)>itemScrollSpeed(speed));});
test('same food fifth pickup activates only that food; another of same group remains safe',()=>{const g=new Game(),apple=byId('apple');for(let i=0;i<4;i++)g.take(apple);assert.notEqual(foodAppearance(apple,g.m).type,'overfed');g.take(apple);assert.equal(foodAppearance(apple,g.m).type,'overfed');assert.notEqual(foodAppearance(byId('banana'),g.m).type,'overfed');assert.ok(g.events.some(e=>e.type==='overfeedStart'));});
test('red overfed pickup applies immediate renewable 3s slowdown without nutrient points',()=>{const g=new Game(),apple=byId('apple');for(let i=0;i<5;i++)g.take(apple);const n=g.m.N,normal=desiredSpeed(g.m);g.take(apple);assert.equal(g.overfedHits,1);assert.equal(g.m.N,n);assert.equal(g.totals[3],6);assert.equal(g.spoiledUntil,3);assert.ok(g.speed<normal);assert.equal(g.events.at(-1).food.kind,'overfed');g.time=1;g.take(apple);assert.equal(g.spoiledUntil,4);assert.equal(g.speed,desiredSpeed(g.m,true));});
test('avoiding overfed food protects nutrition speed during gauge decay; water and damage still reduce it',()=>{const g=new Game();g.records=fullRecords();g.syncMetrics();for(let i=0;i<3;i++)g.take(byId('apple'));assert.equal(g.overfeeding.apple.active,true);const protectedBase=g.overfeeding.apple.protectedNutrition;g.records=[];g.time=10;g.water=100;g.syncMetrics();assert.equal(g.m.F,0);assert.equal(g.m.protectedNutrition,protectedBase);assert.ok(desiredSpeed(g.m)>desiredSpeed(metrics([],100,10)));assert.ok(desiredSpeed(g.m,true)<desiredSpeed(g.m));g.water=0;g.syncMetrics();assert.ok(desiredSpeed(g.m)<protectedBase*C.baseSpeed);g.time=17;g.syncMetrics();assert.equal(g.m.protectedNutrition,0);});
test('overfed red status stays until count falls to two; pause freezes recovery and restart clears it',()=>{const g=new Game();for(let i=0;i<5;i++)g.take(byId('rice'));g.records.splice(0,1);g.syncMetrics();assert.ok(g.m.overfedFoods.includes('rice'));const before=g.m.protectedNutrition;g.step(0);assert.equal(g.m.protectedNutrition,before);g.records.splice(0,2);g.syncMetrics();assert.ok(!g.m.overfedFoods.includes('rice'));assert.ok(g.m.protectedNutrition>0);g.reset();assert.deepEqual(g.overfeeding,{});assert.equal(g.overfedHits,0);});
test('displayed 100 timer excludes pause and resets after any drop below 100',()=>{const g=new Game();g.records=fullRecords();g.speed=30;g.water=100;g.nextSpawn=100;g.step(.99);assert.equal(spaceTarget(g.displayedSpeedKmh,g.topSpeedHeldSec),0);const held=g.topSpeedHeldSec;g.step(0);assert.equal(g.topSpeedHeldSec,held);g.step(.01);assert.equal(spaceTarget(g.displayedSpeedKmh,g.topSpeedHeldSec),1);g.speed=29;g.step(.001);assert.equal(g.topSpeedHeldSec,0);g.speed=30;g.step(.5);assert.equal(spaceTarget(g.displayedSpeedKmh,g.topSpeedHeldSec),0);});
test('finish preserves high-speed ending record before presentation stops and road is restored',()=>{const g=new Game();g.speed=30;g.displayedSpeedKmh=100;g.topSpeedHeldSec=2;g.finish(true);assert.equal(g.finishSnapshot.finishSpeedKmh,100);assert.equal(g.finishSnapshot.hasHighSpeedEnding,true);assert.equal(g.speed,0);assert.equal(g.displayedSpeedKmh,0);assert.equal(g.topSpeedHeldSec,0);assert.equal(spaceTarget(100,2,!!g.finishSnapshot),0);});
