// Execute the real app state machine with tiny DOM/image adapters. This is
// event/state validation, not a substitute for browser or device visual QA.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
async function setup(){
 const elements=new Map();class Element{constructor(){this.hidden=false;this.style={};this.classList={toggle(){}};this.listeners={};this.textContent='';this.innerHTML='';}querySelector(){return this.child??=new Element();}addEventListener(name,fn){this.listeners[name]=fn;}setAttribute(){}click(){this.onclick?.();}getBoundingClientRect(){return {height:720};}setPointerCapture(){}}
 const get=id=>{if(!elements.has(id))elements.set(id,new Element());return elements.get(id);};
 const env={console,Date,Math,Promise,innerHeight:720,innerWidth:1280,performance:{now:()=>0},requestAnimationFrame(){},fetch:async()=>({json:async()=>({})}),Image:class{set src(v){this.value=v;queueMicrotask(()=>this.onload?.());}get src(){return this.value;}async decode(){}},document:{hidden:false,getElementById:get,addEventListener(){}},window:{addEventListener(){}}};
 const context=vm.createContext(env);const code=['config','foods','model'].map(f=>fs.readFileSync(new URL('../dist/'+f+'.js',import.meta.url),'utf8').replace(/^import .*?;\s*$/gm,'').replace(/\bexport /g,'')).join('\n')+'\nconst C=CONFIG;class Renderer{constructor(){this.spin=0;this.pose=0;this.particles=[];}addEffect(){}draw(){}}\n'+fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8').replace(/^import .*?;\s*$/gm,'')+'\nglobalThis.api={game,getStage:()=>stage,getTime:()=>stageTime,startRun,tick,pause,resume,beginEnding,result,resizeState,get:(id)=>$(id),config:C};';
 new vm.Script(code).runInContext(context);await new Promise(r=>setImmediate(r));await new Promise(r=>setImmediate(r));return {a:context.api,context};
}
test('start/decode/countdown/running and pause freeze actual time, hydration and records',async()=>{const {a}=await setup();assert.equal(a.getStage(),'start');a.startRun();assert.equal(a.getStage(),'countdown');a.tick(3);assert.equal(a.getStage(),'running');a.tick(.5);const before=[a.game.time,a.game.water,a.game.records.length];a.pause();a.tick(10);assert.deepEqual([a.game.time,a.game.water,a.game.records.length],before);a.resume();assert.equal(a.getStage(),'running');a.tick(.5);assert.ok(a.game.time>before[0]);});
test('countdown pause resumes same countdown position',async()=>{const {a}=await setup();a.startRun();a.tick(1.2);a.pause();a.tick(5);assert.equal(a.getTime(),1.2);a.resume();a.tick(1.8);assert.equal(a.getStage(),'running');});
test('ending order, display durations and pause; replay preserves snapshot',async()=>{const {a}=await setup();a.game.displayedSpeedKmh=70;a.game.finish(true);const snapshot=a.game.finishSnapshot;a.beginEnding();assert.equal(a.getStage(),'ending1');assert.match(a.get('endingImage').src,/ending-01/);a.tick(1);a.pause();a.tick(20);a.resume();assert.equal(a.getStage(),'ending1');assert.equal(a.getTime(),1);a.tick(.8);assert.equal(a.getStage(),'endingTransition');a.tick(.18);assert.equal(a.getStage(),'ending2');assert.match(a.get('endingImage').src,/ending-02/);a.tick(2.4);assert.equal(a.getStage(),'success');a.get('replay').onclick();assert.equal(a.getStage(),'ending1');assert.equal(a.game.finishSnapshot,snapshot);});
test('skip and restart cancel old ending transitions',async()=>{const {a}=await setup();a.game.displayedSpeedKmh=100;a.game.finish(true);a.beginEnding();a.get('skip').onclick();assert.equal(a.getStage(),'success');a.tick(100);assert.equal(a.getStage(),'success');a.startRun();a.tick(3);assert.equal(a.getStage(),'running');assert.equal(a.game.finishSnapshot,null);assert.equal(a.game.time,0);});
test('rotation pauses; landscape requires explicit resume',async()=>{const {a,context}=await setup();a.startRun();a.tick(3);context.innerHeight=1000;context.innerWidth=500;a.resizeState();assert.equal(a.getStage(),'paused');assert.equal(a.get('rotate').hidden,false);a.resume();assert.equal(a.getStage(),'paused');context.innerHeight=500;context.innerWidth=1000;a.resizeState();assert.equal(a.get('rotate').hidden,true);assert.equal(a.getStage(),'paused');a.resume();assert.equal(a.getStage(),'running');});
test('touch starts without jumping, relative drag clamps, restart clears drag',async()=>{const {a}=await setup();a.startRun();a.tick(3);const canvas=a.get('world');const ev=(y)=>({pointerId:1,clientY:y,preventDefault(){}});const before=a.game.targetY;canvas.listeners.pointerdown(ev(20));assert.equal(a.game.targetY,before);canvas.listeners.pointermove(ev(70));assert.equal(a.game.targetY,before+50);canvas.listeners.pointermove(ev(1000));assert.equal(a.game.targetY,a.config.bike.maxY);a.startRun();a.tick(3);canvas.listeners.pointermove(ev(500));assert.equal(a.game.targetY,a.config.bike.startY);});
