// Execute the real app state machine with tiny DOM/image adapters. This is
// event/state validation, not a substitute for browser or device visual QA.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
async function setup(){
 const elements=new Map();class Element{constructor(){this.hidden=false;this.style={setProperty(){}};this.classList={toggle(){}};this.listeners={};this.textContent='';this.innerHTML='';}querySelector(){return this.child??=new Element();}addEventListener(name,fn){this.listeners[name]=fn;}setAttribute(){}click(){return this.onclick?.();}getBoundingClientRect(){return {width:360,height:640};}setPointerCapture(){}}
 const get=id=>{if(!elements.has(id))elements.set(id,new Element());return elements.get(id);};
 const listeners={};const env={console,Date,Math,Promise,innerHeight:800,innerWidth:390,performance:{now:()=>0},requestAnimationFrame(){},fetch:async()=>({json:async()=>({})}),Image:class{set src(v){this.value=v;queueMicrotask(()=>this.onload?.());}get src(){return this.value;}async decode(){}},document:{hidden:false,getElementById:get,addEventListener(name,fn){listeners[name]=fn;}},window:{addEventListener(){}}};
 const context=vm.createContext(env);const code=['config','bike-manifest','foods','model','view'].map(f=>fs.readFileSync(new URL('../dist/'+f+'.js',import.meta.url),'utf8').replace(/^import .*?;\s*$/gm,'').replace(/\bexport /g,'')).join('\n')+'\nconst C=CONFIG;class Renderer{constructor(){this.particles=[];}resetBike(){}addEffect(){}draw(){}}\n'+fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8').replace(/^import .*?;\s*$/gm,'')+'\nglobalThis.api={game,getStage:()=>stage,getTime:()=>stageTime,startRun,tick,pause,resume,beginEnding,result,resizeState,toggleFullscreen,fullscreenChanged,getDisplay:()=>({portrait,rotated,expanded}),get:(id)=>$(id),config:C};';
 new vm.Script(code).runInContext(context);await new Promise(r=>setImmediate(r));await new Promise(r=>setImmediate(r));return {a:context.api,context};
}
test('start/decode/countdown/running and pause freeze actual time, hydration and records',async()=>{const {a}=await setup();assert.equal(a.getStage(),'start');a.startRun();assert.equal(a.getStage(),'countdown');a.tick(3);assert.equal(a.getStage(),'running');a.tick(.5);const before=[a.game.time,a.game.water,a.game.records.length];a.pause();a.tick(10);assert.deepEqual([a.game.time,a.game.water,a.game.records.length],before);a.resume();assert.equal(a.getStage(),'running');a.tick(.5);assert.ok(a.game.time>before[0]);});
test('countdown pause resumes same countdown position',async()=>{const {a}=await setup();a.startRun();a.tick(1.2);a.pause();a.tick(5);assert.equal(a.getTime(),1.2);a.resume();a.tick(1.8);assert.equal(a.getStage(),'running');});
test('ending order, display durations and pause; replay preserves snapshot',async()=>{const {a}=await setup();a.game.displayedSpeedKmh=70;a.game.finish(true);const snapshot=a.game.finishSnapshot;a.beginEnding();assert.equal(a.getStage(),'ending1');assert.match(a.get('endingImage').src,/ending-01/);a.tick(1);a.pause();a.tick(20);a.resume();assert.equal(a.getStage(),'ending1');assert.equal(a.getTime(),1);a.tick(1.2);assert.equal(a.getStage(),'ending1');a.tick(.1);assert.equal(a.getStage(),'endingTransition');a.tick(.18);assert.equal(a.getStage(),'ending2');assert.match(a.get('endingImage').src,/ending-02/);a.tick(2.4);assert.equal(a.getStage(),'success');a.get('replay').onclick();assert.equal(a.getStage(),'ending1');assert.equal(a.game.finishSnapshot,snapshot);});
test('skip and restart cancel old ending transitions',async()=>{const {a}=await setup();a.game.displayedSpeedKmh=100;a.game.finish(true);a.beginEnding();a.get('skip').onclick();assert.equal(a.getStage(),'success');a.tick(100);assert.equal(a.getStage(),'success');a.startRun();a.tick(3);assert.equal(a.getStage(),'running');assert.equal(a.game.finishSnapshot,null);assert.equal(a.game.time,0);});
test('portrait runs by default and physical rotation does not block gameplay',async()=>{const {a,context}=await setup();a.startRun();a.tick(3);assert.equal(a.getDisplay().portrait,true);context.innerHeight=500;context.innerWidth=1000;a.resizeState();assert.equal(a.getStage(),'running');assert.equal(a.getDisplay().portrait,true);a.pause();a.resume();assert.equal(a.getStage(),'running');});
test('touch starts without jumping, relative portrait drag clamps, restart clears drag',async()=>{const {a}=await setup();a.startRun();a.tick(3);const canvas=a.get('world');const ev=(y)=>({pointerId:1,clientX:100,clientY:y,preventDefault(){}});const before=a.game.targetY;canvas.listeners.pointerdown(ev(20));assert.equal(a.game.targetY,before);canvas.listeners.pointermove(ev(70));assert.ok(a.game.targetY>before&&a.game.targetY<before+100);canvas.listeners.pointermove(ev(1000));assert.equal(a.game.targetY,a.config.bike.maxY);a.startRun();a.tick(3);canvas.listeners.pointermove(ev(500));assert.equal(a.game.targetY,a.config.bike.startY);});
test('unsupported fullscreen falls back to a rotated wide view and exits without score reset',async()=>{const {a}=await setup();a.startRun();a.tick(3);a.tick(.5);const time=a.game.time;await a.toggleFullscreen();assert.equal(a.getDisplay().portrait,false);assert.equal(a.getDisplay().rotated,true);assert.equal(a.getStage(),'running');assert.equal(a.game.time,time);await a.toggleFullscreen();assert.equal(a.getDisplay().portrait,true);assert.equal(a.getDisplay().rotated,false);assert.equal(a.game.time,time);});
test('supported native fullscreen requests landscape and restores default on exit',async()=>{const {a,context}=await setup();let locked=null,unlocked=false;context.screen={orientation:{lock:async value=>{locked=value;context.innerWidth=900;context.innerHeight=450;},unlock:()=>{unlocked=true;}}};a.get('app-shell').requestFullscreen=async()=>{context.document.fullscreenElement=a.get('app-shell');};context.document.exitFullscreen=async()=>{context.document.fullscreenElement=null;};await a.toggleFullscreen();assert.equal(locked,'landscape');assert.equal(a.getDisplay().rotated,false);assert.equal(a.getDisplay().portrait,false);await a.toggleFullscreen();assert.ok(unlocked);assert.equal(a.getDisplay().portrait,true);});
test('rejected fullscreen and orientation lock still allow the fallback view',async()=>{const {a,context}=await setup();a.get('app-shell').requestFullscreen=async()=>{throw new Error('unsupported');};await a.toggleFullscreen();assert.equal(a.getDisplay().rotated,true);await a.toggleFullscreen();a.get('app-shell').requestFullscreen=async()=>{context.document.fullscreenElement=a.get('app-shell');};context.screen={orientation:{lock:async()=>{throw new Error('unsupported');}}};await a.toggleFullscreen();assert.equal(a.getDisplay().rotated,true);});
test('overfeeding activation and red pickup surface the correct UI warnings',async()=>{const {a,context}=await setup();a.startRun();a.tick(3);const apple=vm.runInContext("FOODS.find(f=>f.id==='apple')",context);for(let i=0;i<5;i++)a.game.take(apple);a.tick(.001);assert.match(a.get('hint').textContent,/과영양/);a.game.take(apple);a.tick(.001);assert.match(a.get('hint').textContent,/과영양 음식/);assert.equal(a.game.overfedHits,1);});
test('finish chooses stored high-speed ending after live displayed speed has stopped',async()=>{const {a}=await setup();a.startRun();a.tick(3);a.game.speed=30;a.game.displayedSpeedKmh=100;a.game.finish(true);a.tick(.01);assert.equal(a.getStage(),'finish');assert.equal(a.game.displayedSpeedKmh,0);a.tick(a.config.finishAnimation);assert.equal(a.getStage(),'ending1');assert.equal(a.game.finishSnapshot.finishSpeedKmh,100);});
test('space notifications, pause, first red candy and restart work in the real app state machine',async()=>{const {a,context}=await setup();a.startRun();a.tick(3);a.game.records=vm.runInContext("C.targets.flatMap((n,group)=>Array.from({length:n},()=>({kind:'food',group,foodId:FOODS.find(f=>f.group===group).id,time:0})))",context);a.game.water=100;a.game.speed=30;a.game.nextSpawn=100;a.tick(4);assert.match(a.get('hint').textContent,/우주 돌입/);a.tick(.75);const time=a.game.spaceElapsed;a.pause();a.tick(5);assert.equal(a.game.spaceElapsed,time);a.resume();a.tick(.25);assert.equal(a.game.displayedSpeedKmh,101);a.game.take(vm.runInContext("FOODS.find(f=>f.id==='candy')",context));a.tick(.001);assert.match(a.get('hint').textContent,/80km\/h/);assert.equal(a.game.displayedSpeedKmh,80);a.startRun();a.tick(3);assert.equal(a.game.spaceActive,false);assert.equal(a.game.spaceElapsed,0);});
